config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :cards
  devise_for :users, :controllers => { :registrations => 'registrations'}
  resources :items
  resources :categories
  resources :users

  root to: 'welcome#index'

  get 'admin', to: 'admin#index'
  get 'admin/approvals', to: 'admin#approvals'
  get 'admin/returns', to: 'admin#returns'
  post 'admin/approve', to: 'admin#approve'
  post 'admin/reject', to: 'admin#reject'

  get 'cart', to: 'carts#index'
  post 'cart', to: 'carts#add'
  patch 'cart', to: 'carts#update'
  delete 'cart', to: 'carts#destroy'
  get 'cart/edit/:item_id', to: 'carts#edit', :as => :edit_cart
  get 'cart/clear', to: 'carts#clear'

  get 'order/index', to: 'orders#index'
  post 'order/index', to: 'orders#index'
  get 'order/review', to: 'orders#review'
  post 'order/authenticate', to: 'orders#authenticate'
  post 'order/place', to: 'orders#create'
  get 'order/place', to: 'orders#index'
  get 'order/manage/:id', to: 'orders#manage', :as => :order_manage
  post 'order/return', to: 'orders#return'

  get 'wishlist', to: 'wishlists#index'
  get 'wishlist/add', to: 'wishlists#index'
  post 'wishlist/add', to: 'wishlists#add'
  delete 'wishlist', to: 'wishlists#destroy'
  post 'item/subscribe', to: 'items#subscribe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/feedback.rb
class Feedback < ApplicationRecord
end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController
  before_action :check_admin, only: [:index]
  before_action :set_feedback, only: [:show, :edit, :update, :destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show
  end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit
  end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)

    respond_to do |format|
      if @feedback.save
        format.html { redirect_to @feedback, notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { render :new }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to @feedback, notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_feedback
      @feedback = Feedback.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def feedback_params
      params.require(:feedback).permit(:email, :review)
    end
  # Only admin has the access
    def check_admin
      unless user_signed_in? and current_user.admin
        redirect_to root_path, notice: 'You dont have the rights to access the page'
      end
    end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
        <% feedback.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <%= form.label :review %>
  <div class="field">
    <%= form.text_area :review, :cols => 30, :rows => 10 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<% if user_signed_in? && current_user.admin %>
  <%= link_to 'Back', feedbacks_path %>
<%else %>
  <%= link_to 'Back', root_path %>
<% end %>

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <% if current_user.admin %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'All Users', users_path %></li>
      <li class="list-group-item"><%= link_to 'All Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
      <li class="list-group-item"><%= link_to 'All Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'Approvals', admin_approvals_path %> </li>
      <li class="list-group-item"><%= link_to 'Returns', admin_returns_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
    </ul>
  <%else %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'View Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'View Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
    </ul>
  <%end %>
<% end %>
<h1>Feedbacks</h1>

<table style="..." class="table">
  <thead>
    <tr>
      <th>Email</th>
      <th>Review</th>
      <th>Action</th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.email %></td>
        <td><%= feedback.review %></td>

        <td><%= link_to 'Show', feedback %> |
        <%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Home', admin_path %>

app/views/feedbacks/new.html.erb
<% if user_signed_in? %>
  <ul class="list-group list-group-horizontal">
  <li class="list-group-item"><%= link_to 'View Items', items_path %> </li>
  <li class="list-group-item"><%= link_to 'View Orders', order_index_path %> </li>
  <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
  <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
  <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
  <li class="list-group-item"><%= link_to 'Give Feedback', new_feedback_path %> </li>
  </ul>

<% end %>

<br>

<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', root_path %>

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @feedback.email %>
</p>

<p>
  <strong>Review:</strong>
  <%= @feedback.review %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<% if user_signed_in? && current_user.admin %>
  <%= link_to 'Back', feedbacks_path %>
<%else %>
  <%= link_to 'Back', root_path %>
<% end %>