config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :cards
  devise_for :users, :controllers => { :registrations => 'registrations'}
  resources :items
  resources :categories
  resources :users

  root to: 'welcome#index'

  get 'admin', to: 'admin#index'
  get 'admin/approvals', to: 'admin#approvals'
  get 'admin/returns', to: 'admin#returns'
  post 'admin/approve', to: 'admin#approve'
  post 'admin/reject', to: 'admin#reject'

  get 'cart', to: 'carts#index'
  post 'cart', to: 'carts#add'
  patch 'cart', to: 'carts#update'
  delete 'cart', to: 'carts#destroy'
  get 'cart/edit/:item_id', to: 'carts#edit', :as => :edit_cart
  get 'cart/clear', to: 'carts#clear'

  get 'order/index', to: 'orders#index'
  post 'order/index', to: 'orders#index'
  get 'order/review', to: 'orders#review'
  post 'order/authenticate', to: 'orders#authenticate'
  post 'order/place', to: 'orders#create'
  get 'order/place', to: 'orders#index'
  get 'order/manage/:id', to: 'orders#manage', :as => :order_manage
  post 'order/return', to: 'orders#return'

  get 'wishlist', to: 'wishlists#index'
  get 'wishlist/add', to: 'wishlists#index'
  post 'wishlist/add', to: 'wishlists#add'
  delete 'wishlist', to: 'wishlists#destroy'
  post 'item/subscribe', to: 'items#subscribe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, :brand, :price, :quantity, presence: true
  belongs_to :category
  mount_uploader :image, ItemsUploader

  def get_name
    "#{brand} #{name}"
  end
end

app/controllers/items_controller.rb
# frozen_string_literal: true
class ItemsController < ApplicationController
  before_action :check_admin, except: %i[show index subscribe]
  before_action :set_item, only: %i[show edit update destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
    filters = filter_params
    unless filters.nil?
      filter_items_by_brand(filters[:brand]) unless filters[:brand].empty?
      filter_items_by_category(filters[:category_id]) unless filters[:category_id].empty?
      if filters.has_key?(:availability)
        filter_items_by_availability(filters[:availability])
      end
      if filters.has_key?(:sort)
        sort_items(filters[:sort])
      end
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show; end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit; end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    check_subscriptions
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    delete_item_data
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def subscribe
    subscription = Subscription.new(:item_id => item_params[:id])
    subscription.email = current_user.email
    if Subscription.exists?(:item_id => item_params[:id], :email => subscription.email)
      redirect_to items_path, notice: 'Item already subscribed'
    else
      subscription.save
      redirect_to items_path, notice: 'Item subscribed for alerts'
    end
  end

  private
  # Check if Admin has logged In
  def check_admin
    unless user_signed_in? && current_user.admin
      redirect_to root_path, notice: 'You dont have the rights to access the page'
    end
  end

  # Use callbacks to share common setup or constraints between actions.
  def set_item
    @item = Item.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def item_params
    params.require(:item).permit(:id, :name, :brand, :category_id, :restricted_item,
                                 :age_restricted_item, :quantity, :price, :popularity, :image, :remote_image_url)
  end

  def filter_params
    if params.key?(:filters)
      params.require(:filters).permit(:brand, :category_id, :availability, :sort)
    end
  end

  def filter_items_by_brand(brand)
    @items = @items.select { |item| item.brand == brand }
  end

  def filter_items_by_category(id)
    @items = @items.select { |item| item.category_id == id.to_i }
  end

  def filter_items_by_availability(availability)
    if availability == "A"
      @items = @items.select { |item| item.quantity > 0 }
    else
      @items = @items.select { |item| item.quantity == 0 }
    end
  end

  def sort_items(key)
    if key == "P"
      @items = @items.sort_by(&:popularity).reverse
    elsif key == "C"
      @items = @items.sort_by(&:price)
    end
  end

  def delete_item_data
    id = params[:id]
    Cart.where(item_id: id).destroy_all
    Subscription.where(item_id: id).destroy_all
    Wishlist.where(item_id: id).destroy_all
  end

  # Send Availability Emails
  def check_subscriptions
    if @item.quantity == 0
      parameters = item_params
      if parameters.has_key?(:quantity) and parameters[:quantity].to_i > 0
        @subscriptions = Subscription.where(:item_id => @item.id)
        @subscriptions.each do |subscription|
          SubscriberMailer.subscribe_email(subscription, @item).deliver_now
          subscription.destroy
        end
      end
    end
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= bootstrap_form_with(model: item, local: true) do |form| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <% form.label :brand %>
    <%= form.text_field :brand %>
  </div>
  <div class="field">
    <% form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="field">
    <% form.label :remote_image_url, 'or image URL' %>
    <%= form.text_field :remote_image_url %>
  </div>
  <div>
    <%= form.label :category_id %>
    <%= collection_select( :item, :category_id, Category.all, :id, :name, {}, { multiple: false, include_blank: true }) %>
  </div>
  <div class="field">
    <% form.label :price %>
    <%= form.text_field :price %>
  </div>
  <div class="field"><br>
    <% form.label :restricted_item %>
    <%= form.check_box :restricted_item %>
  </div>
  <div class="field">
    <% form.label :age_restricted_item %>
    <%= form.check_box :age_restricted_item %>
  </div> <br>
  <div class="field">
    <% form.label :quantity %>
    <%= form.number_field :quantity %>
  </div>
  <div class="field">
    <% form.label :popularity %>
    <%= form.text_field :popularity %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/items/_search.html.erb
<%= bootstrap_form_for :filters, :url => {:action => 'index', :controller => "items"}, :method => :get do |form| %>
  <h5>Filter Items</h5>
  <div>
    <p>
      Search By Brand:
      <%= collection_select( :filters, :brand, Item.group(:brand), :brand, :brand, { include_blank: 'Select' }, { multiple: false }) %>
    </p>
  </div>
  <div>
    <p>
      Select By Category:
      <%= collection_select( :filters, :category_id, Category.all, :id, :name, {include_blank: 'Select'}, { multiple: false }) %>
    </p>
  </div>
  <div>
    <p>
      Availability:
      <input id="available" name="filters[availability]" type="radio" value="A" /> Available
      <input id="not_available" name="filters[availability]" type="radio" value="NA" /> Not Available<br />
    </p>
  </div>
  <div>
    <p>
      Sort By:
      <input id="popularity" name="filters[sort]" type="radio" value="P" /> Popularity
      <input id="cost" name="filters[sort]" type="radio" value="C" /> Cost<br />
    </p>
  </div>
  <div class="actions">
    <p>
      <%= form.submit "Apply Filters" %>
      <%= form.submit "Reset Filters" %>
    </p>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<br>
<%= link_to 'All Items', items_path %>

app/views/items/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<% if user_signed_in? %>
  <% if current_user.admin %>
  <ul class="list-group list-group-horizontal">
    <li class="list-group-item"><%= link_to 'All Users', users_path %></li>
    <li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
  <li class="list-group-item"><%= link_to 'All Orders', order_index_path %> </li>
    <li class="list-group-item"><%= link_to 'Approvals', admin_approvals_path %> </li>
    <li class="list-group-item"><%= link_to 'Returns', admin_returns_path %> </li>
  <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
  <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
  <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
  <li class="list-group-item"><%= link_to 'Feedback', feedbacks_path %> </li>
  </ul>
    <%else %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'View Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
      <li class="list-group-item"><%= link_to 'Give Feedback', new_feedback_path %> </li>
    </ul>
    <%end %>
<% end %>

<br>

<h1>Items</h1>
<br>
<div class="card">
  <div class="card-body">
    <%= render 'search' %>
  </div>
</div>

<br>
<table style="width:100%" class="table">
  <thead>
    <tr>
      <th> </th>
      <th>Category</th>
      <th>Brand</th>
      <th colspan>Name</th>
      <th>Age Restricted</th>
      <th>Restricted</th>
      <% if current_user and current_user.admin %>
        <th>Available Quantity</th>
      <% end %>
      <th>Price</th>
      <th>Actions</th>
      <% if current_user and current_user.admin %>
        <th>Admin Actions</th>
      <% end %>
    </tr>

  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= image_tag item.image_url(:thumb).to_s %></td>
        <td><%= item.category.name %></td>
        <td><%= item.brand %></td>
        <td><%= item.name %></td>
        <td><%= item.age_restricted_item %></td>
        <td><%= item.restricted_item %></td>
        <% if current_user and current_user.admin %>
          <td><%= item.quantity %></td>
        <% end %>
        <td><%= item.price %></td>
        <td><%= link_to 'Show', item %> |
        <% if current_user %>
          <%= link_to 'Add to Wishlist', wishlist_add_path(:item_id => item), method: :post %> |
          <% if item.quantity > 0 %>
            <%= link_to 'Add to Cart', cart_path(:item_id => item), method: :post %> |
            <%= link_to 'Buy Now', order_review_path(:item_id => item)%> |
          <% else  %>
            <%= link_to 'Unavailable - Subscribe', item_subscribe_path(:item => {:id => item.id}), method: :post %>
          <%end %></td>
          <td>
          <% if current_user.admin %>
            <%= link_to 'Edit', edit_item_path(item) %> |
            <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
          <%end %>
          </td>
        <%end %>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user and current_user.admin %>
  <%= link_to 'New Item', new_item_path %> <br>
  <%= link_to 'Back to Dashboard', admin_path %>
<% else%>
  <%= link_to 'Home', root_path %>
<%end %>


app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'All Items', items_path %>

app/views/items/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<p>
  <%= image_tag @item.image_url(:big).to_s %>
</p>
<p>
  <strong>Name:</strong>
  <%= @item.name %>
</p>
<p>
  <strong>Brand:</strong>
  <%= @item.brand %>
</p>
  <strong>Category:</strong>
  <%= @item.category_id %>
<p><br>
  <strong>Restricted Item:</strong>
  <%= @item.restricted_item %>
</p>
  <strong>Age Restricted Item:</strong>
  <%= @item.age_restricted_item %>
<p><br>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<%= link_to 'All Items', items_path %> <br>
<% if current_user %>
  <%= link_to 'Buy Now', order_review_path(:item_id => @item)%> <br>
  <% if current_user.admin %>
    <%= link_to 'Edit', edit_item_path(@item)  %>
  <% end %>
<% else%>
  <%= link_to 'Sign In to Buy', new_user_session_path %> <br>
<% end %>
