config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :cards
  devise_for :users, :controllers => { :registrations => 'registrations'}
  resources :items
  resources :categories
  resources :users

  root to: 'welcome#index'

  get 'admin', to: 'admin#index'
  get 'admin/approvals', to: 'admin#approvals'
  get 'admin/returns', to: 'admin#returns'
  post 'admin/approve', to: 'admin#approve'
  post 'admin/reject', to: 'admin#reject'

  get 'cart', to: 'carts#index'
  post 'cart', to: 'carts#add'
  patch 'cart', to: 'carts#update'
  delete 'cart', to: 'carts#destroy'
  get 'cart/edit/:item_id', to: 'carts#edit', :as => :edit_cart
  get 'cart/clear', to: 'carts#clear'

  get 'order/index', to: 'orders#index'
  post 'order/index', to: 'orders#index'
  get 'order/review', to: 'orders#review'
  post 'order/authenticate', to: 'orders#authenticate'
  post 'order/place', to: 'orders#create'
  get 'order/place', to: 'orders#index'
  get 'order/manage/:id', to: 'orders#manage', :as => :order_manage
  post 'order/return', to: 'orders#return'

  get 'wishlist', to: 'wishlists#index'
  get 'wishlist/add', to: 'wishlists#index'
  post 'wishlist/add', to: 'wishlists#add'
  delete 'wishlist', to: 'wishlists#destroy'
  post 'item/subscribe', to: 'items#subscribe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, presence: true
  validates :number, presence: true, length: {minimum: 16, maximum: 16, message: 'should be 16 digits'}
  validates :cvv, presence: true, length: { minimum: 3, maximum: 3, message: 'is a 3-digit PIN'}
  validates :expiry_mm, inclusion: { :in => 1..13, message: '- Invalid Month'}
  validates :expiry_yy, inclusion: { :in => 1..100, message: '- Invalid Year'}
  validate :check_expiry
  belongs_to :user

  private
    def check_expiry
      unless expiry_mm.nil? or expiry_yy.nil?
        if (1...13) === expiry_mm.to_i and (1...100) === expiry_yy.to_i
          expiry_date = Date.new(2000+expiry_yy, expiry_mm, 01)
          if expiry_date.past?
            errors.add(:expiry_mm, "can't be in the past")
          end
        end
      end
    end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :check_logged_in
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.where(:user_id => current_user.id)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
    @card.user_id = current_user.id

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.require(:card).permit(:name, :number, :cvv, :expiry_mm, :expiry_yy)
    end

    def check_logged_in
      unless user_signed_in?
        redirect_to root_path, notice: 'Please Sign In'
      end
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= bootstrap_form_with(model: card, local: true) do |form| %>
  <% if card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
        <% card.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <% form.label :name, 'Name on Card' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <% form.label :number, 'Card Number' %>
    <%= form.text_field :number %>
  </div>

  <div class="field">
    <% form.label :cvv, 'CVV' %>
    <%= form.password_field :cvv %>
  </div>

  <div class="field">
    <% form.label :expiry_mm, 'Expiry MM' %>
    <%= form.number_field :expiry_mm %>
  </div>

  <div class="field">
    <% form.label :expiry_yy, 'Expiry YY' %>
    <%= form.number_field :expiry_yy %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> <br>
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<!--<p id="notice"><%#= notice %></p>-->
<% if user_signed_in? %>
  <% if current_user.admin %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'All Users', users_path %></li>
      <li class="list-group-item"><%= link_to 'All Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'All Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'All Categories', categories_path %></li>
      <li class="list-group-item"><%= link_to 'Approvals', admin_approvals_path %> </li>
      <li class="list-group-item"><%= link_to 'Returns', admin_returns_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'Feedback', feedbacks_path %> </li>
    </ul>
  <%else %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'View Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'View Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'Give Feedback', new_feedback_path %> </li>
    </ul>
  <%end %>
<% end %>
<br>

<h1>Cards</h1>

<% if @cards.empty? %>
  <p>No cards to display</p>
<% else %>
  <table style="width:100%" class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Number</th>
        <th>Cvv</th>
        <th>Expiry mm</th>
        <th>Expiry yy</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
        <% @cards.each do |card| %>
          <tr>
            <td><%= card.name %></td>
            <td><%= card.number %></td>
            <td><%= card.cvv %></td>
            <td><%= card.expiry_mm %></td>
            <td><%= card.expiry_yy %></td>
            <td><%= link_to 'Show', card %> |
            <%= link_to 'Edit', edit_card_path(card) %> |
            <%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
<% end %>

<br>

<%= link_to 'New Card', new_card_path %> <br>
<%= link_to 'Home', root_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<p>
  <strong>Name:</strong>
  <%= @card.name %>
</p>

<p>
  <strong>Number:</strong>
  <%= @card.number %>
</p>

<p>
  <strong>Cvv:</strong>
  <%= @card.cvv %>
</p>

<p>
  <strong>Expiry mm:</strong>
  <%= @card.expiry_mm %>
</p>

<p>
  <strong>Expiry yy:</strong>
  <%= @card.expiry_yy %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> <br>
<%= link_to 'Back', cards_path %>