config/routes.rb
Rails.application.routes.draw do
  resources :feedbacks
  resources :cards
  devise_for :users, :controllers => { :registrations => 'registrations'}
  resources :items
  resources :categories
  resources :users

  root to: 'welcome#index'

  get 'admin', to: 'admin#index'
  get 'admin/approvals', to: 'admin#approvals'
  get 'admin/returns', to: 'admin#returns'
  post 'admin/approve', to: 'admin#approve'
  post 'admin/reject', to: 'admin#reject'

  get 'cart', to: 'carts#index'
  post 'cart', to: 'carts#add'
  patch 'cart', to: 'carts#update'
  delete 'cart', to: 'carts#destroy'
  get 'cart/edit/:item_id', to: 'carts#edit', :as => :edit_cart
  get 'cart/clear', to: 'carts#clear'

  get 'order/index', to: 'orders#index'
  post 'order/index', to: 'orders#index'
  get 'order/review', to: 'orders#review'
  post 'order/authenticate', to: 'orders#authenticate'
  post 'order/place', to: 'orders#create'
  get 'order/place', to: 'orders#index'
  get 'order/manage/:id', to: 'orders#manage', :as => :order_manage
  post 'order/return', to: 'orders#return'

  get 'wishlist', to: 'wishlists#index'
  get 'wishlist/add', to: 'wishlists#index'
  post 'wishlist/add', to: 'wishlists#add'
  delete 'wishlist', to: 'wishlists#destroy'
  post 'item/subscribe', to: 'items#subscribe'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true
  has_many :items
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :check_admin
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    delete_item_data
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Check if Admin has logged In
    def check_admin
      unless user_signed_in? and current_user.admin
        redirect_to root_path, notice: 'You dont have the rights to access the page'
      end
    end

    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name, :tax_slab)
    end
  def delete_item_data
    items = Item.where(category_id: params[:id])
    items.each do |item|
      Cart.where(item_id: item.id).destroy_all
      Subscription.where(item_id: item.id).destroy_all
      Wishlist.where(item_id: item.id).destroy_all
      item.destroy
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
<%= bootstrap_form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%#= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%#= form.label :tax_slab %>
    <%= form.number_field :tax_slab %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<br>
<%= link_to 'All Categories', categories_path %>

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <% if current_user.admin %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'All Users', users_path %></li>
      <li class="list-group-item"><%= link_to 'All Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'All Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'Approvals', admin_approvals_path %> </li>
      <li class="list-group-item"><%= link_to 'Returns', admin_returns_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
      <li class="list-group-item"><%= link_to 'Feedback', feedbacks_path %> </li>
    </ul>
  <%else %>
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item"><%= link_to 'View Items', items_path %> </li>
      <li class="list-group-item"><%= link_to 'View Orders', order_index_path %> </li>
      <li class="list-group-item"><%= link_to 'View Wishlist', wishlist_path %> </li>
      <li class="list-group-item"><%= link_to 'My Cart', cart_path %> </li>
      <li class="list-group-item"><%= link_to 'View Saved Cards', cards_path %> </li>
      <li class="list-group-item"><%= link_to 'Give Feedback', new_feedback_path %> </li>
    </ul>
  <%end %>
<% end %>
<h1>Categories</h1>

<table style="width:100%" class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Tax Rate</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= category.tax_slab %></td>
        <td><%= link_to 'Show', category %> |
        <%= link_to 'Edit', edit_category_path(category) %> |
        <%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %> <br>
<%= link_to 'Back to Dashboard', admin_path %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<!--<p id="notice"><%#= notice %></p>-->

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>
<p>
  <strong>Tax:</strong>
  <%= @category.tax_slab %>
</p>


<%= link_to 'Edit', edit_category_path(@category) %> <br>
<%= link_to 'All Categories', categories_path %>